variable "aws_region" {
  type        = string
  description = "AWS region for Lambda. Default us-east-1 is closest to Wikimedia eqiad in Ashburn, Virginia."
  default     = "us-east-1"
}

variable "project_name" {
  type        = string
  description = "Name prefix for AWS resources."
  default     = "telegram-wikipedia-bot"
}

variable "lambda_zip_path" {
  type        = string
  description = "Path to the Rust Lambda zip generated by scripts/build-lambda.sh."
  default     = "../build/lambda.zip"
}

variable "telegram_bot_token" {
  type        = string
  description = "Telegram bot token from BotFather. Stored in Terraform state."
  sensitive   = true
}

variable "telegram_webhook_secret" {
  type        = string
  description = "Secret sent by Telegram in X-Telegram-Bot-Api-Secret-Token."
  sensitive   = true
}

variable "allowed_telegram_user_ids" {
  type        = string
  description = "Comma-separated Telegram numeric user IDs allowed to use the bot. Empty allows every user."
  default     = ""
}

variable "default_wiki_language" {
  type        = string
  description = "Default Wikipedia language code for searches that cannot be inferred from script."
  default     = "en"
}

variable "favorite_categories" {
  type        = string
  description = "Comma-, pipe-, or newline-separated favorite categories. Entries may be lang:Category title, for example en:Physics|ka:თბილისი."
  default     = ""
}

variable "search_limit" {
  type        = number
  description = "Search/category article button limit. Capped to 20 by the bot."
  default     = 20
}

variable "telegram_message_char_limit" {
  type        = number
  description = "Per-message text split limit. Kept below Telegram's 4096 character limit by default."
  default     = 3900
}

variable "big_article_char_threshold" {
  type        = number
  description = "Article byte size threshold for danger-styled big-article buttons."
  default     = 3900
}

variable "small_article_char_threshold" {
  type        = number
  description = "Article byte size threshold for primary-styled small-article buttons."
  default     = 1000
}

variable "metadata_revision_limit" {
  type        = number
  description = "Last-edit revision count to include in the metadata message. Capped to 50 by the bot."
  default     = 10
}

variable "wikipedia_http_timeout_seconds" {
  type        = number
  description = "HTTP timeout for Telegram and Wikipedia API calls."
  default     = 20
}

variable "ram_cache_max_entries" {
  type        = number
  description = "Maximum entries per in-memory cache namespace. Set 0 to disable the warm Lambda RAM cache."
  default     = 512
}

variable "memory_size_mb" {
  type        = number
  description = "Lambda memory. This account currently accepts up to 3008 MB in us-east-1; raise to 10240 after AWS allows the newer maximum."
  default     = 3008
}

variable "timeout_seconds" {
  type        = number
  description = "Lambda timeout. 900 seconds is the Lambda maximum."
  default     = 900
}

variable "ephemeral_storage_mb" {
  type        = number
  description = "Lambda /tmp storage. 10240 MB is the Lambda maximum."
  default     = 10240
}
